<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-2MCIBL4" failures="1" tests="10" name="Test" time="3.418" errors="0" timestamp="2022-06-02T20:54:04 IST">
  <testcase classname="TEST.Annotation3" name="Akshay" time="0.034"/>
  <testcase classname="TEST.Annotation3" name="Lalit" time="0.004"/>
  <testcase classname="TEST.Annotation3" name="Rahul" time="0.007"/>
  <testcase classname="TEST.Annotation3" name="add" time="0.007"/>
  <testcase classname="TEST.Annotation2" name="testa" time="0.008"/>
  <testcase classname="TEST.Annotation2" name="testa" time="0.014"/>
  <testcase classname="TEST.Annotation2" name="testa" time="0.008"/>
  <testcase classname="TEST.Annotation2" name="teste" time="3.021">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TEST.Annotation2.teste() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TEST.Annotation2.teste() didn't finish within the time-out 3000
at java.base@17.0.1/java.lang.Thread.sleep(Native Method)
at app//TEST.Annotation2.teste(Annotation2.java:21)
at java.base@17.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- teste -->
  <testcase classname="TEST.Annotation2" name="testb" time="0.0">
    <skipped/>
  </testcase> <!-- testb -->
  <testcase classname="TEST.Annotation2" name="testd" time="0.007"/>
  <testcase classname="TEST.Annotation2" name="testc" time="0.0">
    <ignored/>
  </testcase> <!-- testc -->
</testsuite> <!-- Test -->
